name: CI

on:
  push:
  pull_request:

jobs:
  build-test-format-coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            cmake make g++ \
            clang-format \
            gcovr

      - name: Build (includes tests)
        run: 
          ./build_Ut.sh

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-html
          path: report/coverage.html
